In [1]:
import torch 

from torch.nn import functional as F

In [3]:
F.one_hot?

Docstring:
one_hot(tensor, num_classes=-1) -> LongTensor

Takes LongTensor with index values of shape ``(*)`` and returns a tensor
of shape ``(*, num_classes)`` that have zeros everywhere except where the
index of last dimension matches the corresponding value of the input tensor,
in which case it will be 1.

See also `One-hot on Wikipedia`_ .

.. _One-hot on Wikipedia:
    https://en.wikipedia.org/wiki/One-hot

Arguments:
    tensor (LongTensor): class values of any shape.
    num_classes (int):  Total number of classes. If set to -1, the number
        of classes will be inferred as one greater than the largest class
        value in the input tensor.

Returns:
    LongTensor that has one more dimension with 1 values at the
    index of last dimension indicated by the input, and 0 everywhere
    else.

Examples:
    >>> F.one_hot(torch.arange(0, 5) % 3)
    tensor([[1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [1, 0, 0],
            [0, 1, 0]])
    >>> F.one_ho

In [4]:
a = torch.randint(0, 4, (3,4))
a

tensor([[0, 0, 0, 2],
        [2, 2, 3, 2],
        [2, 0, 2, 0]])

In [6]:
F.one_hot(a, 4).permute(2, 0, 1)

tensor([[[1, 1, 1, 0],
         [0, 0, 0, 0],
         [0, 1, 0, 1]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 1],
         [1, 1, 0, 1],
         [1, 0, 1, 0]],

        [[0, 0, 0, 0],
         [0, 0, 1, 0],
         [0, 0, 0, 0]]])

In [8]:
F.cross_entropy?

Signature:
F.cross_entropy(
    input: torch.Tensor,
    target: torch.Tensor,
    weight: Optional[torch.Tensor] = None,
    size_average: Optional[bool] = None,
    ignore_index: int = -100,
    reduce: Optional[bool] = None,
    reduction: str = 'mean',
    label_smoothing: float = 0.0,
) -> torch.Tensor
Docstring:
This criterion computes the cross entropy loss between input logits and target.

See :class:`~torch.nn.CrossEntropyLoss` for details.

Args:
    input (Tensor) : Predicted unnormalized logits;
        see Shape section below for supported shapes.
    target (Tensor) : Ground truth class indices or class probabilities;
        see Shape section below for supported shapes.
    weight (Tensor, optional): a manual rescaling weight given to each
        class. If given, has to be a Tensor of size `C`
    size_average (bool, optional): Deprecated (see :attr:`reduction`). By default,
        the losses are averaged over each loss element in the batch. Note that for
        some 

In [14]:
labels = torch.randint(0, 4, (4,4))
labels.cuda()

tensor([[3, 3, 0, 1],
        [3, 3, 2, 3],
        [1, 0, 3, 3],
        [2, 2, 3, 0]], device='cuda:0')

In [16]:
x  =torch.ones(4,4,4)

In [19]:
F.cross_entropy(x, labels,reduction='none')

tensor([[1.3863, 1.3863, 1.3863, 1.3863],
        [1.3863, 1.3863, 1.3863, 1.3863],
        [1.3863, 1.3863, 1.3863, 1.3863],
        [1.3863, 1.3863, 1.3863, 1.3863]])

In [20]:
F.cross_entropy(x, labels,reduction='none', ignore_index=3)

tensor([[0.0000, 0.0000, 1.3863, 1.3863],
        [0.0000, 0.0000, 1.3863, 0.0000],
        [1.3863, 1.3863, 0.0000, 0.0000],
        [1.3863, 1.3863, 0.0000, 1.3863]])

In [23]:
'_'.join(['', '3', '4'])

'_3_4'

In [24]:
d = {'a':1, 'b':2}

In [25]:
d

{'a': 1, 'b': 2}

In [26]:
d.a

AttributeError: 'dict' object has no attribute 'a'